name: Java CI-CD

on:
  push:
    branches: ['master']

jobs:
  build-test:
    runs-on:  ubuntu-latest

    steps:
      - name: checkout the code 
        uses: actions/checkout@v3

      - name: setup java 17
        uses: actions/checkout@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache:  maven 

      - name: build with maven 
        run: mvn clean install 

      - name: test with maven 
        run:  mvn test 

      - name: Sonar Analysis 
        uses: actions/check@v2 
      
      - name: sonarqube scan 
        uses: sonarqube/sonarqube-scan-action@master 
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      
